[package]
name = "inger"
version = "0.0.0"

[lib]
crate-type = ["dylib"]
harness = false

[dependencies]
libc = "*"

[dependencies.gotcha]
path = "external/libgotcha"

[dependencies.signal]
path = "internal/libsignal"

[dependencies.timetravel]
path = "external/libtimetravel"

[workspace]
