[package]
name = "inger"
version = "0.0.0"

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "*"

[dependencies.gotcha]
path = "external/libgotcha"

[dependencies.timetravel]
path = "external/libtimetravel"
